### ISSUE TITLE
Random Crash when Synced on MongoActionReader

### ISSUE THREAD

**Issue by leordev** [EOSIO/demux-js-eos#23]
Using the MongoActionRead, sometimes, randomly, I receive this exception:

```
(node:48004) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'transactions' of undefined
    at MongoBlock.collectActionsFromBlock (/Users/leoribero/Workspace/phomo-news/services/backend/node_modules/demux-eos/dist/MongoBlock.js:14:49)
    at new MongoBlock (/Users/leoribero/Workspace/phomo-news/services/backend/node_modules/demux-eos/dist/MongoBlock.js:5:29)
    at MongoActionReader.<anonymous> (/Users/leoribero/Workspace/phomo-news/services/backend/node_modules/demux-eos/dist/MongoActionReader.js:54:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/leoribero/Workspace/phomo-news/services/backend/node_modules/demux-eos/dist/MongoActionReader.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:48004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:48004) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

It only happens when demux is synced with the chain (which I believe it tries to read a next block number without this block being created)...

This is my demux instance declaration:
```
  const db = await MassiveProvider.getMassive()

  const actionHandler = new MassiveActionHandler(
    updaters,
    effects,
    db,
    dbConfig.schema,
  )
  // const actionReader = new NodeosActionReader(chainConfig.httpEndpoint, 1)
  const actionReader = new MongoActionReader(
    mongoDbConfig.host,
    50,
    false,
    600,
    mongoDbConfig.dbName,
  )

  await actionReader.initialize()

  const actionWatcher = new BaseActionWatcher(actionReader, actionHandler, 250)

  actionWatcher.watch()
```

**Comment by TaraTritt** [comment]
I'm experiencing the same issue, with the error described above
